[web/data] Remove broken backward compatibility function
popupLoginBox() was deprecated in favor of cw.htmlhelpers.popupLoginBox()
However, the use of cw.utils.deprecatedFunction() is broken. In firebug:

    >>> popupLoginBox()

    TypeError: newfunc is undefined     cubicweb.js:113 (ligne 13)


This function was modified back in 2010, so it's been broken for 4 years.
Let's just get rid of it.  Closes #4042978