[web/calendar] fix regression in previous changeset
"Enables css customization in CalendarView" was untested, and introduced a crash:

  TypeError: not all arguments converted during string formatting