[tests] add a __main__ handler
the relative import in test_rest_api.py needs to be modified to prevent a

  ValueError: Attempted relative import in non-package